version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-ctn
    ports:
      - "5672:5672"      # Port AMQP
      - "15672:15672"    # Port Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
